// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJ6KXdOOV2pwDf4KHg21-D1Om1YA0s5g',
    appId: '1:564539289323:web:00dba2ae56eab4a65ed8ae',
    messagingSenderId: '564539289323',
    projectId: 'fir-firebase-setup-a6b41',
    authDomain: 'fir-firebase-setup-a6b41.firebaseapp.com',
    storageBucket: 'fir-firebase-setup-a6b41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFHpNNK5cUC16Fo7B_yNECWSIQcF-KNg',
    appId: '1:564539289323:android:1b791e68997aa6225ed8ae',
    messagingSenderId: '564539289323',
    projectId: 'fir-firebase-setup-a6b41',
    storageBucket: 'fir-firebase-setup-a6b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIbA5iADfB5QUui0_BjQh8ZQ1EUCjyqg',
    appId: '1:564539289323:ios:4639b9353d9cdd945ed8ae',
    messagingSenderId: '564539289323',
    projectId: 'fir-firebase-setup-a6b41',
    storageBucket: 'fir-firebase-setup-a6b41.appspot.com',
    iosBundleId: 'com.example.demoFirebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiIbA5iADfB5QUui0_BjQh8ZQ1EUCjyqg',
    appId: '1:564539289323:ios:560190bce45201825ed8ae',
    messagingSenderId: '564539289323',
    projectId: 'fir-firebase-setup-a6b41',
    storageBucket: 'fir-firebase-setup-a6b41.appspot.com',
    iosBundleId: 'com.example.demoFirebaseSetup.RunnerTests',
  );
}
